version: '3.1'

services:
  thunderbird:
    image: thunderbird_projektxd_addon_140_11_1esr
    build:
      context: ./thunderbird/
      dockerfile: Dockerfile
    container_name: thunderbird_projektxd_addon
    volumes:
      - thunderbirddata:/data
      - ./built/ProjektXD-1.0.xpi:/data/ProjektXD.xpi
      - ./dist/:/data/projektxd
      #- ./dist:/data/.thunderbird/Og3joltt.default/extensions/findnow@pegenau.de/
    ports:
      - "127.0.0.1:8080:8080"

volumes:
  thunderbirddata:
    external: true
    name: findnow_tbplugin_thunderbirddata